# Generated by Django 5.2.17 on 2026-08-18 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_pwa_session_transfer'),
        ('learning', '0002_contentunit_is_downloadable_default_false'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(max_length=12)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отозван')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.UUIDField(db_index=True)),
                ('public_key_jwk', models.JSONField()),
                ('public_key_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-first_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='DeviceChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge', models.CharField(max_length=43)),
                ('installation_id', models.UUIDField()),
                ('public_key_jwk', models.JSONField()),
                ('public_key_fingerprint', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_generation', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='RecoveryChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='learner_enrollment_unique',
        ),
        migrations.RemoveConstraint(
            model_name='learnersession',
            name='learner_one_active_session',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='learner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('manual', 'Вручную')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='learnersession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnersession',
            name='pass_generation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnersession',
            name='revoke_reason',
            field=models.CharField(blank=True, choices=[('replaced', 'Заменена'), ('manual', 'Вручную'), ('logout', 'Выход'), ('expired', 'Истекла')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='learnersession',
            name='session_token_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отозван'), ('expired', 'Истёк')], default='active', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='learner_enrollment_unique'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_passes', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='learnersession',
            name='access_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='learner.accesspass'),
        ),
        migrations.AddField(
            model_name='device',
            name='access_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='learner.accesspass'),
        ),
        migrations.AddField(
            model_name='learnersession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='learner.device'),
        ),
        migrations.AddConstraint(
            model_name='learnersession',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('access_pass',), name='learner_session_one_active_per_pass'),
        ),
        migrations.AddField(
            model_name='devicechallenge',
            name='access_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='learner.accesspass'),
        ),
        migrations.AddField(
            model_name='offlinelicense',
            name='access_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_licenses', to='learner.accesspass'),
        ),
        migrations.AddField(
            model_name='offlinelicense',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_licenses', to='learning.course'),
        ),
        migrations.AddField(
            model_name='offlinelicense',
            name='course_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_licenses', to='learning.courserevision'),
        ),
        migrations.AddField(
            model_name='offlinelicense',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_licenses', to='learner.device'),
        ),
        migrations.AddField(
            model_name='recoverychallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoverychallenge',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_challenges', to='vendors.vendor'),
        ),
        migrations.AddConstraint(
            model_name='accesspass',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('vendor', 'user'), name='access_pass_one_active_per_user_vendor'),
        ),
        migrations.AddIndex(
            model_name='devicechallenge',
            index=models.Index(fields=['access_pass', 'used_at', 'expires_at'], name='device_challenge_active_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverychallenge',
            index=models.Index(fields=['user', 'used_at', 'expires_at'], name='recovery_challenge_active_idx'),
        ),
    ]
