# Generated by Django 5.2.17 on 2026-08-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0007_delete_pwasessiontransfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessLink',
        ),
    ]
