# Generated by Django 5.2.17 on 2026-08-18 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent_summary', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='vendors.vendor')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['vendor', 'created_at'], name='audit_vendor_created_idx'), models.Index(fields=['event_type', 'created_at'], name='audit_event_created_idx')],
            },
        ),
    ]
