# Generated by Django 5.2.17 on 2026-08-12 16:02

import django.db.models.deletion
import learning.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('module', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('short_description', models.TextField(blank=True)),
                ('description_markdown', models.TextField(blank=True, validators=[learning.validators.validate_markdown_without_html])),
                ('cover_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_courses', to='media_assets.mediaasset')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], default='draft', max_length=16)),
                ('offline_revision', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='vendors.vendor')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CourseRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('snapshot_json', models.JSONField()),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='learning.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_course_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('course', '-revision_number'),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_courses', to='learning.courserevision'),
        ),
        migrations.CreateModel(
            name='CourseRevisionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_revisions', to='media_assets.mediaasset')),
                ('course_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_assets', to='learning.courserevision')),
            ],
        ),
        migrations.CreateModel(
            name='ContentUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('audio', 'Аудио'), ('image', 'Изображение')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('text_markdown', models.TextField(blank=True, null=True, validators=[learning.validators.validate_markdown_without_html])),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_units', to='media_assets.mediaasset')),
                ('is_downloadable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_units', to='learning.lesson')),
            ],
            options={
                'ordering': ('lesson', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.course')),
            ],
            options={
                'ordering': ('course', 'position'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.module'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.UniqueConstraint(fields=('course', 'revision_number'), name='learning_revision_course_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('vendor', 'slug'), name='learning_course_vendor_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='courserevisionasset',
            constraint=models.UniqueConstraint(fields=('course_revision', 'media_asset'), name='learning_revision_asset_unique'),
        ),
        migrations.AddConstraint(
            model_name='contentunit',
            constraint=models.UniqueConstraint(fields=('lesson', 'position'), name='learning_unit_lesson_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='contentunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_asset__isnull', True), ('text_markdown__gt', ''), ('text_markdown__isnull', False), ('type', 'text')), models.Q(('media_asset__isnull', False), ('text_markdown__isnull', True), ('type__in', ('video', 'audio', 'image'))), _connector='OR'), name='learning_unit_content_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='contentunit',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='learning_unit_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='learning_module_course_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='learning_module_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'position'), name='learning_lesson_module_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='learning_lesson_position_positive'),
        ),
    ]
